### ISSUE TITLE
Bookmarklet feature

### ISSUE THREAD

**Issue by nibreh** [sebcode/b#1]
HI!  Very nice app, I like the minimalism !

A bookmarklet will be nice, what do you think about ?

For now I use this trick: http://codepen.io/Realto619/pen/RPGaVd

Juh

**Comment by sebcode** [comment]
Excellent idea, thanks for the suggestion.

I just added bookmarklets similar to your solution in the latest commit, it's accessible via `/[username]/bookmarklet`
