### ISSUE TITLE
bookmarklet.php reads a config.php which is supposed to be in htdocs

### ISSUE THREAD

**Issue by aoloe** [sebcode/b#10]
https://github.com/sebcode/b/blob/29584190cb3a7c079e9c6b80e904669b6e68abcf/htdocs/bookmarklet.php#L3

`bookmarklet.php` reads a `config.php` which is supposed to be in `htdocs`:

- i would avoid to require a `config.php` to be in htdocs. i would read it from `__DIR__/../conf/`, instead
- i could not find in the documentation how  `config.php` should look like...

**Comment by sebcode** [comment]
config.php isn't needed anymore, should be fixed
