### ISSUE TITLE
returning mixed crashes in (at least) php 7.4.26

### ISSUE THREAD

**Issue by aoloe** [sebcode/b#11]
https://github.com/sebcode/b/blob/29584190cb3a7c079e9c6b80e904669b6e68abcf/src/BookmarkManager.php#L85

returning mixed crashes for me in (at least) php 7.4.26

i guess that if you want to use types, you should rather use:

```php
public function getConfig(string $key): ?string
```

this will work as long as -- i think to understand -- the configs are done by `putenv`, which will always return a string (or false... but you're catching that branch in `putenv()`)

**Comment by sebcode** [comment]
php 8 is required as defined in dockerfile :)

nevertheless, agreed that `mixed` is incorrect here. should be fixed in 720b3d464e568833dfb94595862eee70bdd28c44
