### ISSUE TITLE
I don't think it's a good idea to define the namespace in index.php

### ISSUE THREAD

**Issue by aoloe** [sebcode/b#14]
https://github.com/sebcode/b/blob/29584190cb3a7c079e9c6b80e904669b6e68abcf/htdocs/index.php#L3

technically it probably works.

but up to now, I've only seen the `namespace` used where the functions and classes are defined, not where they are used.

not a big issue, but that did let me wonder what was going on...

this will probably be my last ticket for now.
b now works on my computer and i will upload it to my server and start using it.
thanks for sharing your code!

**Comment by sebcode** [comment]
agreed, fixed
thanks for the feedback :D
