### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by nibreh** [sebcode/b#4]
How about to add a pagination system ? 

For example, in `config.php`, we can choose how much link we want to display. Maybe this can be useful when there are many links to display. But I don't know if it's necessary or possible and simple to do.

**Comment by nibreh** [comment]
I found this http://listjs.com/ and I use this trick with **[b](https://github.com/sebcode/b)**: 
http://listjs.com/examples/pagination

Cheers

**Comment by sebcode** [comment]
Makes sense for a massive amount of bookmarks. Just added configurable infinite scrolling, I think that should do the job.
