### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by sjev** [sebcode/b#6]
I'm trying to setup B on a remote server through ftp. The site should run in a subdomain.
_http://testing.meplaza.nl/index.php?configtest_  gives an 'OK', but going trying to access the site results in 'Page not found.'  How to fix this?

**Comment by aitte2** [comment]
"Page not found" means you are not visiting a user-page (`/theusername`). Read the readme again.

**Comment by bertalanp99** [comment]
I have the same issue... But I get Apache errors if trying to access `theusername`, since it's empty and it doesn't have an index file...

**Comment by sebcode** [comment]
The `RewriteRule` redirects all requests to `index.php`. If the rewrite rule doesn't work for you, it's possible that your apache lacks mod_rewrite. Make sure it's enabled in `httpd.conf` like

`LoadModule rewrite_module lib/httpd/modules/mod_rewrite.so`

hth
