### ISSUE TITLE
BookManager says "baseDir not defined in config.php" but no config.php is read before the object is created

### ISSUE THREAD

**Issue by aoloe** [sebcode/b#9]
https://github.com/sebcode/b/blob/29584190cb3a7c079e9c6b80e904669b6e68abcf/src/BookmarkManager.php#L27 

but `index.php` doe not read `config.php`.

**Comment by aoloe** [comment]
in my local copy of `index.php`, i 've now added just before the main `try{}`:

```php
require_once __DIR__.'/../conf/config.php';
```

the config content is:

```php
<?php

putenv('BASE_DIR='.__DIR__.'/../db/');
putenv('BASE_URI=/bookmark/htdocs/');
putenv('INFINITE_SCROLLING=200');
```

this having been said, nowadays, i'm more used to defining an array in `config.php` or even a function that returns an array:

config.php

```php
return function() {
    return [
          'key' => 'value',
    ];
};
```

which can be called in `index.php` as

```php
$config = (include('../conf/config.php`))()
```

which is probably overkill for this project but has the nice property, that you can avoid polluting the global name space (and gives you a chance to pass an argument to the config file, as an example for production and test servers) and is very explicit in the variables being created.

looks strange at first, but on gets used to it...

**Comment by sebcode** [comment]
config.php is legacy stuff, I just forgot to remove that require_once.
"the new way" is to put it into the `.env` file, docker will pick that up

if you're not using docker I guess a `.htaccess` with `SetEnv` would work too

your custom config.php works too of course
